function com_immanitas_crazybelts_GwtDefinition(){var gb='',db=' top: -1000px;',Db='" for "gwt:onLoadErrorFn"',Bb='" for "gwt:onPropertyErrorFn"',mb='");',Eb='#',Qb='&',tc='.cache.js',Gb='/',Mb='//',fc='3A2DD9A3AB14EE4109F7A240083E2A18',oc='62092FA33AE37166BB352B0907DE4485',pc='68C9CFA1F7CF6429E98E220315FEDCE2',sc=':',vb='::',Gc=':moduleBase',fb='<!doctype html>',hb='<html><head><\/head><body><\/body><\/html>',yb='=',Fb='?',Ab='Bad handler "',qc='C3A8EEC7BF569C39AE6F3DA339561125',eb='CSS1Compat',kb='Chrome',jb='DOMContentLoaded',$='DUMMY',rc='E48D89FA9C3A52695F305B4CE832C78E',Fc='Ignoring non-whitelisted Dev Mode URL: ',Tb='Unexpected exception in locale detection, using default: ',Rb='_',Ec='__gwtDevModeHook:com.immanitas.crazybelts.GwtDefinition',Sb='__gwt_Locale',Dc='_gwt_dummy_',Lb='base',Jb='baseUrl',V='begin',_='body',U='bootstrap',Ib='clear.cache.gif',Y='com.immanitas.crazybelts.GwtDefinition',dc='com.immanitas.crazybelts.GwtDefinition.devmode.js',Kb='com.immanitas.crazybelts.GwtDefinition.nocache.js',ub='com.immanitas.crazybelts.GwtDefinition::',xb='content',ec='de_DE',gc='default',Ob='en_UK',Ac='end',hc='es_ES',lb='eval("',Cc='file:',ic='fr_FR',_b='gecko',ac='gecko1_8',W='gwt.codesvr.com.immanitas.crazybelts.GwtDefinition=',X='gwt.codesvr=',zc='gwt/chrome/chrome.css',Cb='gwt:onLoadErrorFn',zb='gwt:onPropertyErrorFn',wb='gwt:property',rb='head',xc='href',Bc='http:',Yb='ie10',$b='ie8',Zb='ie9',ab='iframe',Hb='img',jc='it_IT',ob='javascript',bb='javascript:""',kc='jp_JP',lc='ko_KO',uc='link',yc='loadExternalRefs',Nb='locale',Pb='locale=',sb='meta',qb='moduleRequested',pb='moduleStartup',Xb='msie',tb='name',cb='position:absolute; width:0; height:0; border:none; left: -1000px;',vc='rel',mc='ru_RU',Wb='safari',nb='script',cc='selectingPermutation',Z='startup',wc='stylesheet',ib='undefined',bc='unknown',Ub='user.agent',Vb='webkit',nc='zh_HK';var s=window;var t=document;v(U,V);function u(){var a=s.location.search;return a.indexOf(W)!=-1||a.indexOf(X)!=-1}
function v(a,b){if(s.__gwtStatsEvent){s.__gwtStatsEvent({moduleName:Y,sessionId:s.__gwtStatsSessionId,subSystem:Z,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_immanitas_crazybelts_GwtDefinition.__sendStats=v;com_immanitas_crazybelts_GwtDefinition.__moduleName=Y;com_immanitas_crazybelts_GwtDefinition.__errFn=null;com_immanitas_crazybelts_GwtDefinition.__moduleBase=$;com_immanitas_crazybelts_GwtDefinition.__softPermutationId=0;com_immanitas_crazybelts_GwtDefinition.__computePropValue=null;com_immanitas_crazybelts_GwtDefinition.__getPropMap=null;com_immanitas_crazybelts_GwtDefinition.__gwtInstallCode=function(){};com_immanitas_crazybelts_GwtDefinition.__gwtStartLoadingFragment=function(){return null};var w=function(){return false};var A=function(){return null};__propertyErrorFunction=null;var B=s.__gwt_activeModules=s.__gwt_activeModules||{};B[Y]={moduleName:Y};var C;function D(){G();return C}
function F(){G();return C.getElementsByTagName(_)[0]}
function G(){if(C){return}var a=t.createElement(ab);a.src=bb;a.id=Y;a.style.cssText=cb+db;a.tabIndex=-1;t.body.appendChild(a);C=a.contentDocument;if(!C){C=a.contentWindow.document}C.open();var b=document.compatMode==eb?fb:gb;C.write(b+hb);C.close()}
function H(k){function l(a){function b(){if(typeof t.readyState==ib){return typeof t.body!=ib&&t.body!=null}return /loaded|complete/.test(t.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(t.removeEventListener){t.removeEventListener(jb,d,false)}if(e){clearInterval(e)}}}
if(t.addEventListener){t.addEventListener(jb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=F();var f=D();var g;if(navigator.userAgent.indexOf(kb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(lb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(mb));g=f.createElement(nb);g.language=ob;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(nb);g.language=ob;g.text=c[i];e.appendChild(g);d(e,g)}}}
com_immanitas_crazybelts_GwtDefinition.onScriptDownloaded=function(a){l(function(){m(a)})};v(pb,qb);var n=t.createElement(nb);n.src=k;t.getElementsByTagName(rb)[0].appendChild(n)}
com_immanitas_crazybelts_GwtDefinition.__startLoadingFragment=function(a){return K(a)};com_immanitas_crazybelts_GwtDefinition.__installRunAsyncCode=function(a){var b=F();var c=D().createElement(nb);c.language=ob;c.text=a;b.appendChild(c);b.removeChild(c)};function I(){var c={};var d;var e;var f=t.getElementsByTagName(sb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,gb);if(j.indexOf(vb)>=0){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=gb}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}A=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_immanitas_crazybelts_GwtDefinition.__errFn=e}
function J(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=0?a.substring(0,d+1):gb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=t.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=A(Jb);if(a!=null){return a}return gb}
function h(){var a=t.getElementsByTagName(nb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return gb}
function i(){var a=t.getElementsByTagName(Lb);if(a.length>0){return a[a.length-1].href}return gb}
function j(){var a=t.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==gb){k=h()}if(k==gb){k=i()}if(k==gb&&j()){k=e(t.location.href)}k=f(k);return k}
function K(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_immanitas_crazybelts_GwtDefinition.__moduleBase+a}
function L(){var k=[];var l=0;function m(a,b){var c=k;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var n=[];var o=[];function p(a){var b=o[a](),c=n[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
o[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Qb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=A(Nb)}if(!b){var h=navigator.browserLanguage?navigator.browserLanguage:navigator.language;if(h){var i=h.split(/[-_]/);if(i.length>1){i[1]=i[1].toUpperCase()}b=i.join(Rb)}}if(!b){b=s[Sb]}if(b){c=b}while(b&&!w(Nb,b)){var j=b.lastIndexOf(Rb);if(j<0){b=null;break}b=b.substring(0,j)}}catch(a){alert(Tb+a)}s[Sb]=c;return b||Ob};n[Nb]={de_DE:0,'default':1,en_UK:2,es_ES:3,fr_FR:4,it_IT:5,jp_JP:6,ko_KO:7,ru_RU:8,zh_HK:9};o[Ub]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Vb)!=-1}())return Wb;if(function(){return b.indexOf(Xb)!=-1&&t.documentMode>=10}())return Yb;if(function(){return b.indexOf(Xb)!=-1&&t.documentMode>=9}())return Zb;if(function(){return b.indexOf(Xb)!=-1&&t.documentMode>=8}())return $b;if(function(){return b.indexOf(_b)!=-1}())return ac;return bc};n[Ub]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};w=function(a,b){return b in n[a]};com_immanitas_crazybelts_GwtDefinition.__getPropMap=function(){var a={};for(var b in n){if(n.hasOwnProperty(b)){a[b]=p(b)}}return a};com_immanitas_crazybelts_GwtDefinition.__computePropValue=p;s.__gwt_activeModules[Y].bindings=com_immanitas_crazybelts_GwtDefinition.__getPropMap;v(U,cc);if(u()){return K(dc)}var q;try{m([ec,Wb],fc);m([gc,Wb],fc);m([Ob,Wb],fc);m([hc,Wb],fc);m([ic,Wb],fc);m([jc,Wb],fc);m([kc,Wb],fc);m([lc,Wb],fc);m([mc,Wb],fc);m([nc,Wb],fc);m([ec,Yb],oc);m([gc,Yb],oc);m([Ob,Yb],oc);m([hc,Yb],oc);m([ic,Yb],oc);m([jc,Yb],oc);m([kc,Yb],oc);m([lc,Yb],oc);m([mc,Yb],oc);m([nc,Yb],oc);m([ec,$b],pc);m([gc,$b],pc);m([Ob,$b],pc);m([hc,$b],pc);m([ic,$b],pc);m([jc,$b],pc);m([kc,$b],pc);m([lc,$b],pc);m([mc,$b],pc);m([nc,$b],pc);m([ec,Zb],qc);m([gc,Zb],qc);m([Ob,Zb],qc);m([hc,Zb],qc);m([ic,Zb],qc);m([jc,Zb],qc);m([kc,Zb],qc);m([lc,Zb],qc);m([mc,Zb],qc);m([nc,Zb],qc);m([ec,ac],rc);m([gc,ac],rc);m([Ob,ac],rc);m([hc,ac],rc);m([ic,ac],rc);m([jc,ac],rc);m([kc,ac],rc);m([lc,ac],rc);m([mc,ac],rc);m([nc,ac],rc);q=k[p(Nb)][p(Ub)];var r=q.indexOf(sc);if(r!=-1){l=parseInt(q.substring(r+1),10);q=q.substring(0,r)}}catch(a){}com_immanitas_crazybelts_GwtDefinition.__softPermutationId=l;return K(q+tc)}
function M(){if(!s.__gwt_stylesLoaded){s.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=t.createElement(uc);b.setAttribute(vc,wc);b.setAttribute(xc,K(a));t.getElementsByTagName(rb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
v(yc,V);c(zc);v(yc,Ac)}
I();com_immanitas_crazybelts_GwtDefinition.__moduleBase=J();B[Y].moduleBase=com_immanitas_crazybelts_GwtDefinition.__moduleBase;var N=L();if(s){var O=!!(s.location.protocol==Bc||s.location.protocol==Cc);s.__gwt_activeModules[Y].canRedirect=O;function P(){var b=Dc;try{s.sessionStorage.setItem(b,b);s.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(O&&P()){var Q=Ec;var R=s.sessionStorage[Q];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(R)){if(R&&(window.console&&console.log)){console.log(Fc+R)}R=gb}if(R&&!s[Q]){s[Q]=true;s[Q+Gc]=J();var S=t.createElement(nb);S.src=R;var T=t.getElementsByTagName(rb)[0];T.insertBefore(S,T.firstElementChild||T.children[0]);return false}}}M();v(U,Ac);H(N);return true}
com_immanitas_crazybelts_GwtDefinition.succeeded=com_immanitas_crazybelts_GwtDefinition();