
(function(){var log=function(arg){if(console&&console.log){console.log.call(console,arguments);}};var Slider=function(container,configuration){var config={callback:null,initPosition:2,focusClass:"focusItem"};for(var k in configuration){config[k]=configuration[k]||config[k];}
var holder=$(container);var slider_ul=$('ul',holder);var slider_items=$('li',holder);var initialSize=slider_items.length;$(slider_items[0]).before($(slider_items[initialSize-2]).clone());$(slider_items[0]).before($(slider_items[initialSize-1]).clone());$(slider_items[initialSize-1]).after($(slider_items[1]).clone());$(slider_items[initialSize-1]).after($(slider_items[0]).clone());slider_items=$('li',holder);var currentPosition=2;var transferX=0;var slider_this=this;var touching=false;var startTouchPosition={};var lastTouchPosition={};var sliding=false;slider_ul.css('width',slider_items.length*slider_items.width()+10);this.slideTo=function(newPosition,smooth){var np=newPosition+2;if(np<currentPosition){move(slider_items.width()*initialSize);}
this._slideTo(np,smooth);};this._slideTo=function(newPosition,smooth){log('currentPosition',currentPosition);currentPosition=newPosition;var newX=holder.width()*0.5-slider_items.width()*(newPosition+0.5);move(newX-transferX,smooth);if(typeof config.callback=='function'){config.callback.call(holder,(currentPosition-2+initialSize)%initialSize);}
slider_items.removeClass(config.focusClass);$(slider_items[currentPosition]).addClass(config.focusClass);};this.slidePre=function(){this._slideTo(currentPosition-1,true);};this.slideNext=function(){this._slideTo(currentPosition+1,true);};this.onResize=function(){slider_ul.css('width',slider_items.length*slider_items.width()+10);this._slideTo(currentPosition,false);};var move=function(dx,smooth){log(dx,smooth);transferX=transferX+dx;if(smooth){var time=Math.abs(dx/slider_items.width()*0.5);slider_ul.css("-webkit-transition","-webkit-transform "+time+"s linear 0");}else{slider_ul.css("-webkit-transition","");}
slider_ul.css("-webkit-transform",'translate('+transferX+'px,0px)');};this.onTouchStart=function(evt){if(!touching){log('touchStart',evt);touching=true;lastTouchPosition=evt;startTouchPosition=evt;sliding=false;}};this.onTouchMove=function(evt){if(touching){sliding=true;move(evt.x-lastTouchPosition.x);lastTouchPosition=evt;evt.origEvent.preventDefault();return false;}};this.onTouchEnd=function(evt){if(touching&&sliding){log('touchEnd',evt);move(evt.x-lastTouchPosition.x);lastTouchPosition=evt;if(Math.abs(evt.x-startTouchPosition.x)>50){if(transferX>-slider_items.width()){move(-slider_items.width()*initialSize);currentPosition=currentPosition+initialSize;}else if(transferX<holder.width()-slider_items.width()*(initialSize+3)){move(slider_items.width()*initialSize);currentPosition=currentPosition-initialSize;}
if(evt.x-startTouchPosition.x>50){this.slidePre();}else{this.slideNext();}}else{this._slideTo(currentPosition);}
evt.origEvent.preventDefault();}
touching=false;return false;};var getTouch=function(evt){if(evt.touches||evt.targetTouches||evt.changedTouches){return(evt.changedTouches[0]||evt.touches[0]||evt.targetTouches[0]);}
else if(evt.originalEvent){return getTouch(evt.originalEvent);}
else{return null;}};var abstractPositionEvent=function(origEvent){var touch=getTouch(origEvent);if(touch){return{x:touch.clientX,y:touch.clientY,origEvent:origEvent};}
else if(origEvent.pageX||origEvent.pageY){return{x:origEvent.pageX,y:origEvent.pageY,origEvent:origEvent};}};holder.on('mousedown',function(evt){slider_this.onTouchStart(abstractPositionEvent(evt));return false;});holder.on('mousemove',function(evt){slider_this.onTouchMove(abstractPositionEvent(evt));});holder.on('mouseup',function(evt){slider_this.onTouchEnd(abstractPositionEvent(evt));});holder.on('mouseout',function(evt){slider_this.onTouchEnd(abstractPositionEvent(evt));});holder.on('touchstart',function(evt){slider_this.onTouchStart(abstractPositionEvent(evt));});holder.on('touchmove',function(evt){slider_this.onTouchMove(abstractPositionEvent(evt));});holder.on('touchend',function(evt){slider_this.onTouchEnd(abstractPositionEvent(evt));});holder.on('touchcancel',function(evt){slider_this.onTouchEnd(abstractPositionEvent(evt));});this._slideTo(currentPosition);return this;};window.Slider=Slider;})();/*  |xGv00|686d9492f1d98baaa2acab8a97e3e5b2 */