var GAME=GAME||{};GAME.GameObjectPool=function(a){this.classType=a;this.pool=[]};GAME.GameObjectPool.constructor=GAME.GameObjectPool;GAME.GameObjectPool.prototype.getObject=function(){var a=this.pool.pop();a||(a=new this.classType);return a};GAME.GameObjectPool.prototype.returnObject=function(){};var PIXI=PIXI||{};
PIXI.StressTest=function(a){this.callback=a;this.stage=new PIXI.Stage;this.renderer=PIXI.autoDetectRenderer(500,500);document.body.appendChild(this.renderer.view);this.cover=document.createElement("div");this.cover.style.width=this.cover.style.height="500px";this.cover.style.background="#25284a";document.body.appendChild(this.cover);this.renderer.view.style.position="absolute";this.cover.style.position="absolute";this.cover.style.zIndex=2;this.duration=3;var b=this;this.texture=PIXI.Texture.fromImage("img/testImage.png");
this.texture.baseTexture.addEventListener("loaded",function(){b.begin()});this.frameRate=[]};PIXI.StressTest.constructor=PIXI.StressTest;PIXI.StressTest.prototype.begin=function(){this.testSprites=[];for(var a=0;300>a;a++){var b=new PIXI.Sprite(this.texture);b.anchor.x=0.5;b.anchor.y=0.5;this.stage.addChild(b);b.position.x=50+400*Math.random();b.position.y=50+400*Math.random();this.testSprites.push(b)}this.renderer.render(this.stage);this.startTime=Date.now();this.lastTime=Date.now();var c=this;requestAnimFrame(function(){c.update()})};
PIXI.StressTest.prototype.update=function(){for(var a=Date.now(),b=0;b<this.testSprites.length;b++)this.testSprites[b].rotation+=0.3;this.renderer.render(this.stage);b=a-this.lastTime;this.frameRate.push(0.06*b);this.lastTime=a;if(a-this.startTime<1E3*this.duration){var c=this;requestAnimFrame(function(){c.update()})}else document.body.removeChild(this.renderer.view),document.body.removeChild(this.cover),this.renderer=this.cover=null,this.result=this.frameRate.length/this.duration,this.callback&&
this.callback()};GAME=GAME||{};
GAME.Background=function(){PIXI.DisplayObjectContainer.call(this);this.width=1E3;this.scrollPosition=1500;this.foggyTrees=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("05_far_BG.jpg"),40,this);this.rearSilhouette=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("03_rear_silhouette.png"),358,this);this.rearCanopy=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("03_rear_canopy.png"),0,this);this.tree1=PIXI.Sprite.fromFrame("02_tree_1.png");this.tree1.anchor.x=0.5;this.addChild(this.tree1);this.tree2=
PIXI.Sprite.fromFrame("02_tree_2.png");this.tree2.anchor.x=0.5;this.tree2.position.y=50;this.addChild(this.tree2);this.farCanopy=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("02_front_canopy.png"),0,this);this.vines=new GAME.Vines(this);this.roofLeaves=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("00_roof_leaves.png"),0,this);this.frontSilhouette=new GAME.BackgroundElement(PIXI.Texture.fromFrameId("01_front_silhouette.png"),424,this);this.foggyTrees.speed=0.5;this.rearSilhouette.speed=
0.6;this.rearCanopy.speed=0.6;this.farCanopy.speed=0.75;this.frontSilhouette.speed=0.8;this.roofLeaves.speed=1};GAME.Background.constructor=GAME.Background;GAME.Background.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
GAME.Background.prototype.updateTransform=function(){this.scrollPosition=GAME.camera.x+4E3;var a=1.5*-this.scrollPosition/2,a=a%(this.width+556),a=a+(this.width+556),a=a-this.tree1.width/2;this.tree1.position.x=a-GAME.xOffset;a=1.5*-(this.scrollPosition+this.width/2)/2;a%=this.width+556;a+=this.width+556;a-=this.tree2.width/2;this.tree2.position.x=a-GAME.xOffset;this.foggyTrees.setPosition(this.scrollPosition);this.rearSilhouette.setPosition(this.scrollPosition);this.rearCanopy.setPosition(this.scrollPosition);
this.farCanopy.setPosition(this.scrollPosition);this.frontSilhouette.setPosition(this.scrollPosition);this.roofLeaves.setPosition(this.scrollPosition);this.vines.setPosition(this.scrollPosition);PIXI.DisplayObjectContainer.prototype.updateTransform.call(this)};
GAME.Vines=function(a){this.vines=[];this.owner=a;for(var b=0;10>b;b++){var c=new PIXI.Sprite.fromFrame("01_hanging_flower3.png");c.offset=100*b+50*Math.random();c.speed=(1.5+0.25*Math.random())/2;c.position.y=-200*Math.random();a.addChild(c);c.position.x=200;this.vines.push(c)}this.speed=1};GAME.Vines.prototype.setPosition=function(a){for(var b=0;b<this.vines.length;b++){var c=this.vines[b],d=-(a+c.offset)*c.speed,d=d%this.owner.width,d=d+this.owner.width;c.position.x=d}};
GAME.Background.prototype.joyRideMode=function(){};GAME.Background.prototype.normalMode=function(){};GAME.BackgroundElement=function(a,b,c){this.sprites=[];this.spriteWidth=a.width-1;var d=Math.ceil(940/this.spriteWidth);3>d&&(d=3);for(var e=0;e<d;e++){var f=new PIXI.Sprite(a);f.position.y=b;c.addChild(f);this.sprites.push(f)}this.speed=1};
GAME.BackgroundElement.prototype.setPosition=function(a){for(var b=this.spriteWidth,c=0;c<this.sprites.length;c++){var d=-a*this.speed,d=d+c*b,d=d%(b*this.sprites.length),d=d+2*b;this.sprites[c].position.x=Math.floor(d)-GAME.xOffset}};GAME=GAME||{};
GAME.Lava=function(a){this.textures=[PIXI.Texture.fromFrameId("lava_slosh_01.png"),PIXI.Texture.fromFrameId("lava_slosh_02.png"),PIXI.Texture.fromFrameId("lava_slosh_03.png"),PIXI.Texture.fromFrameId("lava_slosh_04.png"),PIXI.Texture.fromFrameId("lava_slosh_05.png"),PIXI.Texture.fromFrameId("lava_slosh_06.png"),PIXI.Texture.fromFrameId("lava_slosh_07.png"),PIXI.Texture.fromFrameId("lava_slosh_08.png"),PIXI.Texture.fromFrameId("lava_slosh_07.png"),PIXI.Texture.fromFrameId("lava_slosh_06.png"),PIXI.Texture.fromFrameId("lava_slosh_05.png"),
PIXI.Texture.fromFrameId("lava_slosh_04.png"),PIXI.Texture.fromFrameId("lava_slosh_03.png"),PIXI.Texture.fromFrameId("lava_slosh_02.png"),PIXI.Texture.fromFrameId("lava_slosh_01.png")];console.log(this.textures);var b=this.textures[0];this.sprites=[];this.spriteWidth=b.width-1;var c=8;3>c&&(c=3);console.log(c);for(var d=0;d<c;d++){var e=new PIXI.Sprite(b);e.position.y=580;a.addChild(e);this.sprites.push(e)}this.speed=1;this.count=this.offset=0};
GAME.Lava.prototype.setPosition=function(a){var b=this.spriteWidth,c=this.count%this.textures.length,c=Math.floor(c);this.offset+=2.5;a+=this.offset;this.count+=0.3;for(var d=0;d<this.sprites.length;d++){var e=-a*this.speed,e=e+d*b,e=e%(b*this.sprites.length),e=e+2*b;this.sprites[d].setTexture(this.textures[c]);this.sprites[d].position.x=Math.floor(e)+800-GAME.xOffset}};GAME=GAME||{};GAME.JoyBackground=function(){PIXI.DisplayObjectContainer.call(this);this.width=1E3;this.scrollPosition=1500;this.swoosh=new GAME.BackgroundElement(PIXI.Texture.fromImage("img/stretched_hyper_tile.jpg"),0,this);this.swoosh.speed=0.7;this.scale.y=1.7;this.scale.x=4};GAME.JoyBackground.constructor=GAME.LowFiBackground;GAME.JoyBackground.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
GAME.JoyBackground.prototype.updateTransform=function(){this.scrollPosition=GAME.camera.x+4E3;this.swoosh.setPosition(this.scrollPosition);PIXI.DisplayObjectContainer.prototype.updateTransform.call(this)};GAME=GAME||{};GAME.LowFiBackground=function(){PIXI.DisplayObjectContainer.call(this);this.width=1E3;this.scrollPosition=1500;this.swoosh=new GAME.BackgroundElement(PIXI.Texture.fromImage("img/iP4_BGtile.jpg"),0,this);this.swoosh.speed=0.7};GAME.LowFiBackground.constructor=GAME.LowFiBackground;GAME.LowFiBackground.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
GAME.LowFiBackground.prototype.updateTransform=function(){this.scrollPosition=GAME.camera.x+4E3;this.swoosh.setPosition(this.scrollPosition);PIXI.DisplayObjectContainer.prototype.updateTransform.call(this)};GAME=GAME||{};
GAME.RprView=function(a){this.engine=a;this.renderer=PIXI.autoDetectRenderer(600,800);GAME.HIGH_MODE=this.renderer instanceof PIXI.WebGLRenderer;this.stage=new PIXI.Stage;this.container=new PIXI.DisplayObjectContainer;this.hud=new PIXI.DisplayObjectContainer;this.game=new PIXI.DisplayObjectContainer;this.gameFront=new PIXI.DisplayObjectContainer;this.container.addChild(this.game);this.container.addChild(this.gameFront);this.stage.addChild(this.container);this.stage.addChild(this.hud);this.normalBackground=
GAME.lowMode?new GAME.LowFiBackground:new GAME.Background(this.gameFront);this.joyBackground=new GAME.JoyBackground;this.lava=new GAME.Lava(this.gameFront);this.powerBar=new GAME.PowerBar;this.score=new GAME.Score;this.score.position.x=300;this.background=this.normalBackground;this.game.addChild(this.background);this.hud.addChild(this.powerBar);this.hud.addChild(this.score);this.trail=new GAME.SteveTrail(this.game);this.trail2=new GAME.SteveTrailFire(this.game);this.powerBar.alpha=0;this.count=this.score.alpha=
0;this.zoom=1;this.white=PIXI.Sprite.fromImage("img/whiteSquare.jpg");GAME.xOffset=this.container.position.x;this.dust=new GAME.PixiDust;this.container.addChild(this.dust);this.splash=new GAME.Splash;this.splash.position.y=300;this.splash.position.x=300;this.game.addChild(this.splash)};GAME.RprView.constructor=GAME.RprView;
GAME.RprView.prototype.showHud=function(){this.score.alpha=1;this.score.position.x=GAME.width+300;TweenLite.to(this.score.position,1,{x:GAME.width-295-20,ease:Elastic.easeOut});this.powerBar.alpha=1;this.powerBar.position.x=GAME.width;TweenLite.to(this.powerBar.position,1,{x:GAME.width-295,ease:Elastic.easeOut,delay:0.3})};GAME.RprView.prototype.hideHud=function(){};
GAME.RprView.prototype.update=function(){this.count+=0.01;if(!GAME.lowMode){var a=-GAME.width/2;this.container.position.x=(a+(-this.engine.steve.view.position.x-a)*(this.zoom-1))*this.zoom;this.container.position.y=-this.engine.steve.view.position.y*this.zoom;this.container.position.x+=GAME.width/2;this.container.position.y+=GAME.height/2;GAME.xOffset=this.container.position.x;0<this.container.position.y&&(this.container.position.y=0);a=-GAME.height*this.zoom;a+=GAME.height;this.container.position.y<
a&&(this.container.position.y=a);this.container.scale.x=this.zoom;this.container.scale.y=this.zoom}this.trail.target=this.engine.steve;this.trail2.target=this.engine.steve;this.trail.update();this.trail2.update();this.dust.update();this.lava.setPosition(GAME.camera.x+4E3);this.score.setScore(Math.round(this.engine.score));this.powerBar.bar.scale.x=this.engine.pickupCount/(50*this.engine.bulletMult)*(248/252);this.renderer.render(this.stage)};
GAME.RprView.prototype.joyrideMode=function(){this.game.removeChild(this.background);this.background=this.joyBackground;this.game.addChildAt(this.background,0);this.stage.addChild(this.white);this.white.alpha=1;TweenLite.to(this.white,0.7,{alpha:0,ease:Sine.easeOut})};GAME.RprView.prototype.doSplash=function(){this.splash.splash(this.engine.steve.position)};
GAME.RprView.prototype.normalMode=function(){this.game.removeChild(this.background);this.background=this.normalBackground;this.game.addChildAt(this.background,0);this.stage.addChild(this.white);this.white.alpha=1;TweenLite.to(this.white,0.5,{alpha:0,ease:Sine.easeOut})};
GAME.RprView.prototype.resize=function(a,b){GAME.width=a;GAME.height=b;this.renderer.resize(a,b);this.background.width=a;this.score.position.x=a-295-20;this.score.position.y=12;this.white.scale.x=a/16;this.white.scale.y=b/16;this.powerBar.position.x=a-295;this.powerBar.position.y=12};var GAME=GAME||{},laserCount=0;GAME.CollisionManager=function(a){this.engine=a};GAME.CollisionManager.constructor=GAME.CollisionManager;GAME.CollisionManager.prototype.update=function(){this.playerVsBlock();this.playerVsPickup();this.playerVsFloor()};
GAME.CollisionManager.prototype.playerVsBlock=function(){for(var a=this.engine.enemyManager.enemies,b=this.engine.steve,c=0;c<a.length;c++){var d=a[c],e=d.position.x-b.position.x;e>-d.width/2&&e<d.width/2&&(e=d.position.y-b.position.y,e>-d.height/2-20&&e<d.height/2&&!b.joyRiding&&(b.die(),this.engine.gameover(),d.hit()))}};
GAME.CollisionManager.prototype.playerVsPickup=function(){for(var a=this.engine.pickupManager.pickups,b=this.engine.steve,c=0;c<a.length;c++){var d=a[c];if(!d.isPickedUp){var e=d.position.x-b.position.x;e>-d.width/2&&e<d.width/2&&(e=d.position.y-b.position.y,e>-d.height/2&&e<d.height/2&&(this.engine.pickupManager.removePickup(c),this.engine.pickup()))}}};
GAME.CollisionManager.prototype.playerVsFloor=function(){var a=this.engine.floorManager.floors,b=this.engine.steve,c=a.length;b.onGround=!1;if(610<b.position.y)if(this.engine.isPlaying)b.boil(),this.engine.view.doSplash(),this.engine.gameover();else{b.speed.x*=0.95;interactive||(interactive=!0,this.engine.view.doSplash(),showGameover());return}for(var d=0;d<c;d++){var e=a[d].x-b.position.x+1135;if(477<b.position.y&&0<e&&1135>e){if(b.isDead){b.bounce++;if(2<b.bounce)return;b.view.setTexture(b.crashFrames[b.bounce]);
b.speed.y*=-0.7;b.speed.x*=0.8;b.rotationSpeed=0<b.rotationSpeed?-0.3*Math.random():0==b.rotationSpeed?0.3*Math.random():0}else b.speed.y=-0.3;b.isFlying||(b.position.y=478,b.onGround=!0)}}0>b.position.y&&(b.position.y=0,b.speed.y*=0)};GAME=GAME||{};GAME.FloorManager=function(a){this.engine=a;this.count=0;this.floors=[];this.floorPool=new GAME.GameObjectPool(GAME.Floor)};GAME.FloorManager.constructor=GAME.FloorManager;GAME.FloorManager.prototype.update=function(){for(var a=0;a<this.floors.length;a++){var b=this.floors[a];b.position.x=b.x-GAME.camera.x-16;b.position.x<-1135-GAME.xOffset-16&&(this.floorPool.returnObject(b),this.floors.splice(a,1),a--,this.engine.view.gameFront.removeChild(b))}};
GAME.FloorManager.prototype.addFloor=function(a){var b=this.floorPool.getObject();b.x=a;b.position.y=482;this.engine.view.gameFront.addChild(b);this.floors.push(b)};GAME.FloorManager.prototype.destroyAll=function(){for(var a=0;a<this.floors.length;a++){var b=this.floors[a];console.log(b);this.floorPool.returnObject(b);this.engine.view.gameFront.removeChild(b)}this.floors=[]};GAME.Floor=function(){PIXI.Sprite.call(this,PIXI.Texture.fromFrameId("00_forest_floor.png"))};GAME.Floor.constructor=PIXI.Floor;
GAME.Floor.prototype=Object.create(PIXI.Sprite.prototype);GAME=GAME||{};GAME.SegmentManager=function(a){this.engine=a;this.sections=data;this.count=0;this.currentSegment=data[0];this.startSegment={length:2270,floor:[0,1135],blocks:[],coins:[]};this.chillMode=!0;this.position=this.last=0};GAME.SegmentManager.constructor=GAME.SegmentManager;
GAME.SegmentManager.prototype.reset=function(a){a&&(this.count=0);this.currentSegment=this.startSegment;this.currentSegment.start=-200;for(a=0;a<this.currentSegment.floor.length;a++)this.engine.floorManager.addFloor(this.currentSegment.start+this.currentSegment.floor[a])};
GAME.SegmentManager.prototype.update=function(){this.position=GAME.camera.x+2*width;if(this.position-this.currentSegment.start>this.currentSegment.length)if(this.engine.joyrideMode){var a=this.startSegment;a.start=this.currentSegment.start+this.currentSegment.length;this.currentSegment=a;for(a=0;a<this.currentSegment.floor.length;a++)this.engine.floorManager.addFloor(this.currentSegment.start+this.currentSegment.floor[a])}else{a=this.sections[this.count%this.sections.length];a.start=this.currentSegment.start+
this.currentSegment.length;this.currentSegment=a;for(a=0;a<this.currentSegment.floor.length;a++)this.engine.floorManager.addFloor(this.currentSegment.start+this.currentSegment.floor[a]);for(var b=this.currentSegment.blocks,c=b.length/2,a=0;a<c;a++)this.engine.enemyManager.addEnemy(this.currentSegment.start+b[2*a],b[2*a+1]);b=this.currentSegment.coins;c=b.length/2;for(a=0;a<c;a++)this.engine.pickupManager.addPickup(this.currentSegment.start+b[2*a],b[2*a+1]);this.count++}};var GAME=GAME||{},enemyFrames;GAME.Enemy=function(){this.position=new PIXI.Point;this.view=new PIXI.Sprite(PIXI.Texture.fromFrameId("spike_box.png"));this.view.anchor.x=0.5;this.view.anchor.y=0.5;this.height=this.width=150};GAME.Enemy.constructor=GAME.Enemy;GAME.Enemy.prototype.reset=function(){this.explosion&&(this.view.removeChild(this.explosion),this.explosion.reset());this.view.width=157};
GAME.Enemy.prototype.hit=function(){this.explosion||(this.explosion=new GAME.Explosion);this.explosion.explode();this.view.addChild(this.explosion);this.view.width=1};GAME.Enemy.prototype.update=function(){this.view.position.x=this.position.x-GAME.camera.x;this.view.position.y=this.position.y};GAME=GAME||{};laserCount=0;GAME.EnemyManager=function(a){this.engine=a;this.enemies=[];this.enemyPool=new GAME.GameObjectPool(GAME.Enemy);this.spawnCount=0};GAME.EnemyManager.constructor=GAME.EnemyManager;GAME.EnemyManager.prototype.update=function(){for(var a=0;a<this.enemies.length;a++){var b=this.enemies[a];b.update();b.view.position.x<-100-GAME.xOffset&&!this.engine.steve.isDead&&(this.enemyPool.returnObject(b),this.enemies.splice(a,1),this.engine.view.gameFront.removeChild(b.view),a--)}};
GAME.EnemyManager.prototype.addEnemy=function(a,b){var c=this.enemyPool.getObject();c.position.x=a;c.position.y=b;this.enemies.push(c);this.engine.view.gameFront.addChild(c.view)};GAME.EnemyManager.prototype.destroyAll=function(){for(var a=0;a<this.enemies.length;a++){var b=this.enemies[a];b.reset();this.enemyPool.returnObject(b);this.engine.view.gameFront.removeChild(b.view)}this.enemies=[]};
GAME.EnemyManager.prototype.destroyAllOffScreen=function(){for(var a=0;a<this.enemies.length;a++){var b=this.enemies[a];b.x>GAME.camera.x+GAME.width&&(this.enemyPool.returnObject(b),this.engine.view.game.removeChild(b.view),this.enemies.splice(a,1),a--)}};var GAME=GAME||{},pickupTextures;
GAME.Pickup=function(){pickupTextures||(pickupTextures="pickup_01.png pickup_02.png pickup_03.png pickup_04.png pickup_05.png pickup_06.png pickup_07.png pickup_08.png".split(" "));this.position=new PIXI.Point;this.view=new PIXI.DisplayObjectContainer;this.clip=new PIXI.Sprite(PIXI.Texture.fromFrameId(pickupTextures[Math2.randomInt(0,pickupTextures.length-1)]));this.clip.anchor.x=0.5;this.clip.anchor.y=0.5;this.shine=PIXI.Sprite.fromFrame("pickupShine.png");this.shine.anchor.x=this.shine.anchor.y=
0.5;this.shine.scale.x=this.shine.scale.y=1;this.shine.alpha=0.5;GAME.lowMode||this.view.addChild(this.shine);this.view.addChild(this.clip);this.height=this.width=100;this.count=300*Math.random()};GAME.Pickup.constructor=GAME.Pickup;GAME.Pickup.prototype.reset=function(){};
GAME.Pickup.prototype.update=function(){this.isPickedUp?(this.view.scale.x=1-this.ratio,this.view.scale.y=1-this.ratio,this.position.x=this.pickupPosition.x+(this.steve.position.x-this.pickupPosition.x)*this.ratio,this.position.y=this.pickupPosition.y+(this.steve.position.y-this.pickupPosition.y)*this.ratio):(this.count+=0.1*GAME.time.DELTA_TIME,this.clip.scale.x=0.75+0.1*Math.sin(this.count),this.clip.scale.y=0.75-0.1*Math.cos(this.count),this.clip.rotation=0.2*Math.sin(1.5*this.count),this.shine.rotation=
0.2*this.count);this.view.position.x=this.position.x-GAME.camera.x;this.view.position.y=this.position.y};GAME=GAME||{};laserCount=0;GAME.PickupManager=function(a){this.engine=a;this.pickups=[];this.pickupPool=new GAME.GameObjectPool(GAME.Pickup);this.pos=this.spawnCount=0};GAME.PickupManager.constructor=GAME.PickupManager;
GAME.PickupManager.prototype.update=function(){this.engine.joyrideMode&&(this.spawnCount+=GAME.time.DELTA_TIME,5<this.spawnCount&&(this.pos+=0.15,this.spawnCount=0,this.addPickup(GAME.camera.x+GAME.width,280+180*Math.sin(this.pos))));for(var a=0;a<this.pickups.length;a++){var b=this.pickups[a];b.update();b.isPickedUp?(b.ratio+=0.3*(1-b.ratio)*GAME.time.DELTA_TIME,0.99<b.ratio&&(this.pickupPool.returnObject(b),this.pickups.splice(a,1),this.engine.view.game.removeChild(b.view),a--)):b.view.position.x<
-100-GAME.xOffset&&(this.engine.view.game.removeChild(b.view),this.pickupPool.returnObject(b),this.pickups.splice(a,1),a--)}};GAME.PickupManager.prototype.addPickup=function(a,b){var c=this.pickupPool.getObject();c.position.x=a;c.position.y=b;this.pickups.push(c);this.engine.view.game.addChild(c.view)};GAME.PickupManager.prototype.removePickup=function(a){a=this.pickups[a];a.isPickedUp=!0;a.steve=this.engine.steve;a.pickupPosition={x:a.position.x,y:a.position.y};a.ratio=0};
GAME.PickupManager.prototype.destroyAll=function(){for(var a=0;a<this.pickups.length;a++){var b=this.pickups[a];this.pickupPool.returnObject(b);this.engine.view.game.removeChild(b.view)}this.pickups=[]};GAME.PickupManager.prototype.destroyAllOffScreen=function(){for(var a=0;a<this.pickups.length;a++){var b=this.pickups[a];b.x>GAME.camera.x+GAME.width&&(this.pickupPool.returnObject(b),this.engine.view.game.removeChild(b.view),this.pickups.splice(a,1),a--)}};GAME=GAME||{};GAME.HIGH_MODE=!0;GAME.camera=new PIXI.Point;GAME.height;
GAME.RprEngine=function(){this.onGameover;this.steve=new GAME.Steve;this.view=new GAME.RprView(this);this.segmentManager=new GAME.SegmentManager(this);this.enemyManager=new GAME.EnemyManager(this);this.pickupManager=new GAME.PickupManager(this);this.floorManager=new GAME.FloorManager(this);this.collisionManager=new GAME.CollisionManager(this);this.view.game.addChild(this.steve.view);this.bulletMult=1;this.score=this.pickupCount=0;this.joyrideMode=!1;this.joyrideCountdown=0;this.isPlaying=this.steve.view.visible=
!1;this.levelCount=0};GAME.RprEngine.prototype.start=function(){this.isPlaying=!0;this.score=0;this.steve.level=1;this.steve.position.y=477;this.steve.speed.y=0;this.steve.speed.x=this.steve.baseSpeed;this.steve.view.rotation=0;this.steve.isFlying=!1;this.steve.isDead=!1;this.steve.view.play();this.steve.view.visible=!0;this.segmentManager.chillMode=!1;this.bulletMult=1;this.segmentManager.reset();this.enemyManager.destroyAll();this.pickupManager.destroyAll()};
GAME.RprEngine.prototype.update=function(){GAME.time.update();var a=0;0<a&&(a=0);-70>a&&(a=-70);GAME.camera.y=a;this.steve.update();this.collisionManager.update();this.segmentManager.update();this.floorManager.update();this.enemyManager.update();this.pickupManager.update();this.joyrideMode&&(this.joyrideCountdown-=GAME.time.DELTA_TIME,0>=this.joyrideCountdown&&this.joyrideComplete());this.levelCount+=GAME.time.DELTA_TIME;3600<this.levelCount&&(this.levelCount=0,this.steve.level+=0.05,GAME.time.speed+=
0.05);this.view.update()};GAME.RprEngine.prototype.reset=function(){this.enemyManager.destroyAll();this.floorManager.destroyAll();this.segmentManager.reset();this.view.zoom=1;this.levelCount=this.pickupCount=0;this.steve.level=1;this.view.game.addChild(this.steve.view)};GAME.RprEngine.prototype.joyrideComplete=function(){this.joyrideMode=!1;this.pickupCount=0;this.bulletMult+=0.3;this.view.normalMode();this.steve.normalMode();this.enemyManager.destroyAll()};
GAME.RprEngine.prototype.gameover=function(){this.isPlaying=!1;this.segmentManager.chillMode=!0;interactive=!1;this.onGameover();this.view.game.addChild(this.steve.view);TweenLite.to(this.view,0.5,{zoom:2,ease:Cubic.easeOut})};GAME.RprEngine.prototype.gameoverReal=function(){this.onGameoverReal()};
GAME.RprEngine.prototype.pickup=function(){this.joyrideMode?this.score+=10:(this.score+=10,this.view.score.jump(),this.pickupCount++,this.pickupCount>=50*this.bulletMult&&!this.steve.isDead&&(this.pickupCount=0,this.joyrideMode=!0,this.joyrideCountdown=600,this.view.joyrideMode(),this.steve.joyrideMode(),this.steve.position.x=0,GAME.camera.x=game.steve.position.x-100,this.enemyManager.destroyAll(),this.pickupManager.destroyAll(),this.floorManager.destroyAll(),this.segmentManager.reset()))};
Time=function(){this.DELTA_TIME=1;this.lastTime=Date.now();this.frames=0;this.speed=1};Time.constructor=Time;Time.prototype.update=function(){this.frames++;var a=Date.now();this.frames=0;this.DELTA_TIME=0.06*(a-this.lastTime);this.DELTA_TIME*=this.speed;2.3<this.DELTA_TIME&&(this.DELTA_TIME=2.3);this.lastTime=a};GAME.time=new Time;GAME=GAME||{};
GAME.Countdown=function(){PIXI.DisplayObjectContainer.call(this);this.three=PIXI.Sprite.fromFrame("3Get.png");this.two=PIXI.Sprite.fromFrame("2tricksy.png");this.one=PIXI.Sprite.fromFrame("1pixie.png");this.three.anchor.x=this.three.anchor.y=0.5;this.two.anchor.x=this.two.anchor.y=0.5;this.one.anchor.x=this.one.anchor.y=0.5;this.three.alpha=0;this.two.alpha=0;this.one.alpha=0;this.addChild(this.three);this.addChild(this.two);this.addChild(this.one);this.three.alpha=0;this.two.alpha=0;this.one.alpha=
0};GAME.Countdown.constructor=GAME.Countdown;GAME.Countdown.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
GAME.Countdown.prototype.startCountDown=function(a){this.visible=!0;this.onComplete=a;this.three.alpha=0;this.two.alpha=0;this.one.alpha=0;this.three.scale.x=this.three.scale.y=2;this.two.scale.x=this.two.scale.y=2;this.one.scale.x=this.one.scale.y=2;TweenLite.to(this.three,1*time2,{alpha:1,onComplete:$.proxy(this.onThreeShown,this)});TweenLite.to(this.three.scale,1*time2,{x:1,y:1,ease:Elastic.easeOut})};var time=0.1,time2=0.5,delay=0;
GAME.Countdown.prototype.onThreeShown=function(){TweenLite.to(this.three,1*time,{alpha:0,ease:Sine.easeOut,delay:delay});TweenLite.to(this.three.scale,1*time,{x:0.5,y:0.5,ease:Cubic.easeOut,delay:delay});TweenLite.to(this.two,1*time2,{alpha:1,onComplete:$.proxy(this.onTwoShown,this),delay:delay});TweenLite.to(this.two.scale,1*time2,{x:1,y:1,ease:Elastic.easeOut,delay:delay})};
GAME.Countdown.prototype.onTwoShown=function(){TweenLite.to(this.two,1*time,{alpha:0,delay:delay});TweenLite.to(this.two.scale,1*time,{x:0.5,y:0.5,ease:Cubic.easeOut,delay:delay});TweenLite.to(this.one,1*time2,{alpha:1,onComplete:$.proxy(this.onOneShown,this),delay:delay});TweenLite.to(this.one.scale,1*time2,{x:1,y:1,ease:Elastic.easeOut,delay:delay})};
GAME.Countdown.prototype.onOneShown=function(){TweenLite.to(this.one.scale,1*time,{x:0.5,y:0.5,ease:Cubic.easeOut,delay:delay});TweenLite.to(this.one,1*time,{alpha:0,onComplete:$.proxy(this.onFinish,this),delay:delay});this.onComplete()};GAME.Countdown.prototype.onFinish=function(){this.visible=!1};GAME=GAME||{};
GAME.Steve=function(){this.position=new PIXI.Point;this.runningFrames=[PIXI.Texture.fromFrameId("characterRUNscaled_01.png"),PIXI.Texture.fromFrameId("characterRUNscaled_02.png"),PIXI.Texture.fromFrameId("characterRUNscaled_03.png"),PIXI.Texture.fromFrameId("characterRUNscaled_04.png"),PIXI.Texture.fromFrameId("characterRUNscaled_05.png"),PIXI.Texture.fromFrameId("characterRUNscaled_06.png"),PIXI.Texture.fromFrameId("characterRUNscaled_07.png"),PIXI.Texture.fromFrameId("characterRUNscaled_08.png"),PIXI.Texture.fromFrameId("characterRUNscaled_09.png")];
this.flyingFrames=[PIXI.Texture.fromFrameId("characterFLATflying_01.png"),PIXI.Texture.fromFrameId("characterFLATflying_02.png"),PIXI.Texture.fromFrameId("characterFLATflying_03.png")];this.crashFrames=[PIXI.Texture.fromFrameId("characterFALLscaled3.png"),PIXI.Texture.fromFrameId("characterFALLscaled1.png"),PIXI.Texture.fromFrameId("characterFALLscaled3.png")];this.view=new PIXI.MovieClip(this.flyingFrames);this.view.animationSpeed=0.23;this.view.play();this.view.anchor.x=0.5;this.view.anchor.y=0.5;
this.ground=this.position.y=477;this.gravity=0.3;this.baseSpeed=8;this.speed=new PIXI.Point(this.baseSpeed,0);this.activeCount=0;this.isFlying=!1;this.accel=0;this.width=26;this.height=37;this.onGround=!1;this.rotationSpeed=0;this.joyRiding=!1;this.level=1;this.realAnimationSpeed=0.23};GAME.Steve.constructor=GAME.Steve;GAME.Steve.prototype.update=function(){this.isDead?this.updateDieing():this.updateRunning()};
GAME.Steve.prototype.joyrideMode=function(){this.joyRiding=!0;TweenLite.to(this.speed,0.3,{x:20,ease:Cubic.easeIn});this.realAnimationSpeed=0.92};GAME.Steve.prototype.normalMode=function(){this.joyRiding=!1;TweenLite.to(this.speed,0.6,{x:this.baseSpeed,ease:Cubic.easeOut});this.realAnimationSpeed=0.23};
GAME.Steve.prototype.updateRunning=function(){this.view.animationSpeed=this.realAnimationSpeed*GAME.time.DELTA_TIME*this.level;this.isActive&&(this.isFlying=!0);this.isFlying?(this.accel=0.6,this.speed.y-=this.accel*GAME.time.DELTA_TIME,0<this.speed.y&&(this.speed.y-=0.3*GAME.time.DELTA_TIME)):0>this.speed.y&&(this.speed.y+=0.05*GAME.time.DELTA_TIME);this.speed.y+=this.gravity*GAME.time.DELTA_TIME;8<this.speed.y&&(this.speed.y=8);-9>this.speed.y&&(this.speed.y=-9);this.position.x+=this.speed.x*GAME.time.DELTA_TIME*
this.level;this.position.y+=this.speed.y*GAME.time.DELTA_TIME;this.onGround!=this.onGroundCache&&(this.onGroundCache=this.onGround,this.view.textures=this.onGround?this.runningFrames:this.flyingFrames);GAME.camera.x=this.position.x-100;this.view.position.x=this.position.x-GAME.camera.x;this.view.position.y=this.position.y-GAME.camera.y;this.view.rotation+=0.1*(0.05*this.speed.y-this.view.rotation)};
GAME.Steve.prototype.updateDieing=function(){this.speed.x*=0.999;this.onGround&&(this.speed.y*=0.99);this.speed.y+=0.1;this.accel+=0.1*(0-this.accel)*GAME.time.DELTA_TIME;this.speed.y+=this.gravity*GAME.time.DELTA_TIME;this.position.x+=this.speed.x*GAME.time.DELTA_TIME;this.position.y+=this.speed.y*GAME.time.DELTA_TIME;GAME.camera.x=this.position.x-100;this.view.position.x=this.position.x-GAME.camera.x;this.view.position.y=this.position.y-GAME.camera.y;this.view.rotation=5>this.speed.x?this.view.rotation+
this.rotationSpeed*(this.speed.x/5)*GAME.time.DELTA_TIME:this.view.rotation+this.rotationSpeed*GAME.time.DELTA_TIME};GAME.Steve.prototype.jump=function(){this.isDead&&5>this.speed.x&&(this.isDead=!1,this.speed.x=10);this.position.y!=this.ground?this.isFlying=!0:(this.isActive=!0,this.activeCount=0)};
GAME.Steve.prototype.die=function(){this.isDead||(TweenLite.to(GAME.time,0.5,{speed:0.1,ease:Cubic.easeOut,onComplete:function(){TweenLite.to(GAME.time,2,{speed:1,delay:1})}}),this.isDead=!0,this.bounce=0,this.speed.x=15,this.speed.y=-15,this.rotationSpeed=0.3,this.view.stop(),this.view.setTexture(this.crashFrames[0]))};GAME.Steve.prototype.boil=function(){this.isDead||(this.isDead=!0)};GAME.Steve.prototype.fall=function(){this.isFlying=this.isActive=!1};GAME.SteveTrail=function(a){this.stage=a;this.target=new PIXI.Point;this.particals=[];this.particalPool=new GAME.GameObjectPool(Partical);this.max=100;this.count=0};GAME.SteveTrail.constructor=GAME.SteveTrail;
GAME.SteveTrail.prototype.update=function(){if(this.target.isFlying&&!this.target.isDead&&(this.count++,this.count%3)){var a=this.particalPool.getObject();this.stage.addChild(a);a.position.x=this.target.view.position.x+10*Math.random()-5-20;a.position.y=this.target.view.position.y+50;a.direction=0;a.dirSpeed=0.5<Math.random()?-0.1:0.1;a.sign=this.particals.length%2?-1:1;a.scaly=2*Math.random()-1;a.speed.y=3*this.target.accel;a.alphay=2;a.rotation=2*Math.random()*Math.PI;a.scale.x=a.scale.y=0.2+0.5*
Math.random();this.particals.push(a)}for(var b=0;b<this.particals.length;b++)a=this.particals[b],a.dirSpeed+=0.0030*a.sign,2<a.dirSpeed&&(a.dirSpeed=2),a.direction+=a.dirSpeed,a.speed.x=Math.sin(a.direction),a.speed.y=Math.cos(a.direction),a.position.x+=5*a.speed.x*a.scaly,a.position.y+=3*a.speed.y,a.alphay*=0.85,a.rotation+=0.1*a.speed.x,a.alpha=1<a.alphay?1:a.alphay,0.01>a.alpha&&(this.stage.removeChild(a),this.particals.splice(b,1),this.particalPool.returnObject(a),b--)};
Partical=function(){PIXI.Sprite.call(this,PIXI.Texture.fromFrameId("starPops0004.png"));this.anchor.x=0.5;this.anchor.y=0.5;this.speed=new PIXI.Point};Partical.constructor=Partical;Partical.prototype=Object.create(PIXI.Sprite.prototype);GAME.Explosion=function(){PIXI.DisplayObjectContainer.call(this);this.particals=[];this.top=new ExplosionPartical("asplodeInner02.png");this.bottom=new ExplosionPartical("asplodeInner01.png");this.top.position.y=-20;this.bottom.position.y=20;this.top.position.x=20;this.bottom.position.x=20;this.anchor=new PIXI.Point;this.addChild(this.top);this.addChild(this.bottom);this.particals=[this.top,this.bottom];for(var a=0;5>a;a++)this.particals.push(new ExplosionPartical("asplodeSpike_01.png")),this.particals.push(new ExplosionPartical("asplodeSpike_02.png"));
this.clouds=[];for(a=0;5>a;a++){var b=new PIXI.Sprite.fromFrame("dustSwirl.png");this.clouds.push(b);this.addChild(b)}this.reset()};GAME.Explosion.constructor=GAME.Explosion;GAME.Explosion.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);GAME.Explosion.prototype.explode=function(){this.exploding=!0};
GAME.Explosion.prototype.reset=function(){for(var a=0;5>a;a++){var b=this.clouds[a];b.anchor.x=0.5;b.anchor.y=0.5;b.scaleTarget=2+2*Math.random();b.scale.x=b.scale.x=0.5;b.alpha=0.75;b.position.x=150*(Math.random()-0.5);b.position.y=150*(Math.random()-0.5);b.speed=new PIXI.Point(20*Math.random()-10,20*Math.random()-10);b.state=0;b.rotSpeed=0.05*Math.random()}for(a=0;a<this.particals.length;a++){b=this.particals[a];this.addChild(b);var c=2*a/this.particals.length*Math.PI,d=7+Math.random();b.directionX=
Math.cos(c)*d;b.directionY=Math.sin(c)*d;b.rotation=-c;b.rotationSpeed=0.02*Math.random()}};
GAME.Explosion.prototype.updateTransform=function(){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);if(this.exploding){for(var a=0;a<this.clouds.length;a++){var b=this.clouds[a];b.rotation+=b.rotSpeed;0==b.state?(b.scale.x+=0.4*(b.scaleTarget-b.scale.x),b.scale.y=b.scale.x,b.scale.x>b.scaleTarget-0.1&&(b.state=1)):(b.position.x+=0.05*b.speed.x,b.position.y+=0.05*b.speed.y)}for(a=0;a<this.particals.length;a++)b=this.particals[a],b.directionY+=0.1,b.directionX*=0.99,b.position.x+=b.directionX,
b.position.y+=b.directionY,b.rotation+=b.rotationSpeed}};ExplosionPartical=function(a){PIXI.Sprite.call(this,PIXI.Texture.fromFrameId(a));this.anchor.x=0.5;this.anchor.y=0.5;this.speed=new PIXI.Point};ExplosionPartical.constructor=ExplosionPartical;ExplosionPartical.prototype=Object.create(PIXI.Sprite.prototype);GAME=GAME||{};
GAME.Splash=function(){this.textures=[PIXI.Texture.fromFrameId("lavaFrame_01.png"),PIXI.Texture.fromFrameId("lavaFrame_02.png"),PIXI.Texture.fromFrameId("lavaFrame_03.png"),PIXI.Texture.fromFrameId("lavaFrame_04.png"),PIXI.Texture.fromFrameId("lavaFrame_05.png"),PIXI.Texture.fromFrameId("lavaFrame_06.png"),PIXI.Texture.fromFrameId("lavaFrame_07.png"),PIXI.Texture.fromFrameId("lavaFrame_08.png"),PIXI.Texture.fromFrameId("lavaFrame_09.png"),PIXI.Texture.fromFrameId("lavaFrame_10.png"),PIXI.Texture.fromFrameId("lavaFrame_11.png"),
PIXI.Texture.fromFrameId("lavaFrame_12.png")];PIXI.MovieClip.call(this,this.textures);this.anchor.x=0.5;this.anchor.y=1;this.scale.x=this.scale.y=2;this.animationSpeed=0.3;this.visible=!1;this.realPosition};GAME.Splash.constructor=GAME.Splash;GAME.Splash.prototype=Object.create(PIXI.MovieClip.prototype);GAME.Splash.prototype.splash=function(a){this.realPosition=a.x;this.position.y=620;this.gotoAndPlay(0);this.visible=!0};
GAME.Splash.prototype.updateTransform=function(){this.visible&&(PIXI.MovieClip.prototype.updateTransform.call(this),this.position.x=this.realPosition-GAME.camera.x,this.currentFrame>this.textures.length-1&&(this.stop(),this.visible=!1))};GAME.SteveTrailFire=function(a){this.stage=a;this.target=new PIXI.Point;this.particals=[];this.particalPool=new GAME.GameObjectPool(ParticalFire);this.max=100;this.count=0;this.mOffset=mat3.identity();this.mOffset[2]=-30;this.mOffset[5]=30;this.spare=mat3.identity()};GAME.SteveTrailFire.constructor=GAME.SteveTrailFire;
GAME.SteveTrailFire.prototype.update=function(){if(this.target.isDead&&(this.mOffset,mat3.multiply(this.mOffset,this.target.view.localTransform,this.spare),this.count++,this.count%3)){var a=this.particalPool.getObject();this.stage.addChild(a);a.position.x=this.spare[2];a.position.y=this.spare[5];a.speed.x=1+2*Math.random();a.speed.y=1+2*Math.random();a.speed.x*=-1;a.speed.y*=1;a.alphay=2;a.rotation=2*Math.random()*Math.PI;a.scale.x=a.scale.y=0.2+0.5*Math.random();this.particals.push(a)}for(var b=
0;b<this.particals.length;b++)a=this.particals[b],a.scale.x=a.scale.y*=1.02,a.alphay*=0.85,a.alpha=1<a.alphay?1:a.alphay,a.position.x+=2*a.speed.x,a.position.y+=2*a.speed.y,0.01>a.alpha&&(this.stage.removeChild(a),this.particals.splice(b,1),this.particalPool.returnObject(a),b--)};ParticalFire=function(){PIXI.Sprite.call(this,PIXI.Texture.fromFrameId("fireCloud.png"));this.anchor.x=0.5;this.anchor.y=0.5;this.speed=new PIXI.Point};ParticalFire.constructor=ParticalFire;ParticalFire.prototype=Object.create(PIXI.Sprite.prototype);GAME.PixiDust=function(){PIXI.DisplayObjectContainer.call(this);this.particals=[];this.particalPool=new GAME.GameObjectPool(ParticalDust);this.max=GAME.HIGH_MODE?100:10;for(var a=this.count=0;a<this.max;a++){var b=this.particalPool.getObject();b.home.x=Math.random()*-GAME.width;b.position.y=b.home.y=110640*Math.random();b.speed=new PIXI.Point(0.2*(Math.random()-0.5),0.4*(Math.random()-0.5));this.particals.push(b);this.addChild(b)}this.focalLength=150};GAME.PixiDust.constructor=GAME.PixiDust;
GAME.PixiDust.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);GAME.PixiDust.prototype.update=function(){for(var a=0;a<this.particals.length;a++){var b=this.particals[a],c=this.focalLength/(this.focalLength+b.z),c=this.focalLength/(this.focalLength+b.z);b.scale.x=b.scale.y=c;b.home.x+=b.speed.x;b.position.y+=b.speed.y;b.position.x=1.5*(b.home.x-GAME.camera.x)*c;b.position.x%=GAME.width;0>b.position.x&&(b.position.x+=GAME.width);b.position.y%=640;0>b.position.y&&(b.position.y+=640)}};
ParticalDust=function(){ParticalDust.globalCount++;PIXI.Sprite.call(this,PIXI.Texture.fromFrameId(ParticalDust.frames[ParticalDust.globalCount%3]));this.anchor.x=0.5;this.anchor.y=0.5;this.z=500*Math.random();this.rotation=2*Math.random()*Math.PI;this.home=new PIXI.Point;this.alpha=0.5};ParticalDust.globalCount=0;ParticalDust.frames=["mote01.png","mote02.png","mote03.png"];ParticalDust.constructor=Partical;ParticalDust.prototype=Object.create(PIXI.Sprite.prototype);GAME=GAME||{};GAME.PowerBar=function(){PIXI.DisplayObjectContainer.call(this);this.barBG=PIXI.Sprite.fromFrame("bulletTime_back.png");this.addChild(this.barBG);this.barBG.position.x=20;this.barBG.position.y=30;this.bar=PIXI.Sprite.fromFrame("powerFillBar.png");this.addChild(this.bar);this.bar.position.x=20;this.bar.position.y=30;this.frame=PIXI.Sprite.fromFrame("bulletTime_BG.png");this.addChild(this.frame);this.position.x=100};GAME.PowerBar.constructor=GAME.PowerBar;GAME.PowerBar.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);GAME=GAME||{};GAME.Score=function(){PIXI.DisplayObjectContainer.call(this);this.ratio=0;this.glyphs={"0":"number_00.png",1:"number_01.png",2:"number_02.png",3:"number_03.png",4:"number_04.png",5:"number_05.png",6:"number_06.png",7:"number_07.png",8:"number_08.png",9:"number_09.png",",":"number_comma.png"};for(a in this.glyphs)this.glyphs[a]=PIXI.Texture.fromFrameId(this.glyphs[a]);this.digits=[];for(var a=0;8>a;a++)this.digits[a]=new PIXI.Sprite(this.glyphs[a]),this.addChild(this.digits[a]);this.setScore(formatScore(12345))};
GAME.Score.constructor=PIXI.Score;GAME.Score.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);GAME.Score.prototype.setScore=function(a){a=formatScore(a).split("");for(var b=0,c=0;c<a.length;c++){var d=this.digits[c];d.visible=!0;d.setTexture(this.glyphs[a[c]]);d.position.x=b;b+=d.width+-10}for(c=0;c<this.digits.length;c++)this.digits[c].position.x-=b;for(c=a.length;c<this.digits.length;c++)this.digits[c].visible=!1};GAME.Score.prototype.jump=function(){this.ratio=2.2};
function formatScore(a){a=a.toString().split("");for(var b="",c=a.length,d=c%3-1,e=0;e<c;e++)b+=a[e],0==(e-d)%3&&e!=c-1&&(b+=",");return b};