
var LANGUAGES = ["en_GB","nl_NL"];

var LANGUAGE = {
	"loading":				["LOADING",				"LADEN"],
	"moreGames":			["More Games",			"Meer Spellen"],
	"start":				["Start",				"Start"],
	"shop":					["Store",				"Winkel"],
	"music":				["music",				"muziek"],
	"on":					["on",					"aan"],
	"off": 					["off",					"uit"],
	"back": 				["Back",				"Terug"],
	"map": 					["Map",					"Kaart"],
	"selectPower": 			["Select Power",		"Kies Kracht"],
	"powerUps.headstart": 	["Head start",			"Voorsprong"],
	"powerUps.extraLife": 	["Extra life",			"Extra leven"],
	"powerUps.magnet": 		["Egg magnet",			"Eimagneet"],
	"youHave": 				["You have $",			"Je hebt er $"],
	"tapPowerOnOff":		["Tap a power to turn it on/off",
	                		 						"Druk op een kracht om aan/uit te zetten"],
	"time": 				["Time:",				"Tijd:"],
	"bumpText": 			["Whoops!;Snap!;Watch it!;Careful!;Boom!;Bump!",
	            			 						"Oeps!;Oei!;Pas op!;Hé!;Kijk uit!;Bam!"],
	"youFailed": 			["You failed...",		"Je hebt gefaald..."],
	"wellDone": 			["Well done!",			"Goed gedaan!"],
	"eggs": 				["Eggs: $",				"Eieren: $"],
	"score": 				["Score: $",			"Score: $"],
	"hits": 				["Hits: $",				"Botsingen: $"],
	"replay": 				["Replay",				"Opnieuw"],
	
	"tutorial.welcome":	["Run, Kaiju, Run!\nYour goal is to reach the end of the\nlevel and collect as many eggs as possible.",
	                            		 			"Ren, Kaiju, Ren!\nJe doel is om het einde van het level te halen\nen zo veel mogelijk eitjes te verzamelen."],
	"tutorial.welcome.keyboard":	["Press the left/right\narrow keys to steer.",
	                            		                            		 			"Stuur met de\nlinks/rechtstoetsen."],
	"tutorial.welcome.touch":		["Touch the bottom left/right\nof the screen to steer.",
	                            		                            		 			"Stuur door links/rechts-\nonder te drukken."],
	"tutorial.dodge":		["What's that?\nIt looks dangerous,\nbetter steer around it!",
													"Wat is dat?\nHet ziet er gevaarlijk uit,\nje kunt er maar beter omheen lopen."],
	"tutorial.jump":	["If you can't go around,\ngo up!",
										            "Als je er niet omheen kunt,\nmoet je de lucht in!"],
	"tutorial.jump.keyboard":	["Press the up key\nto jump.",
											"Druk op de omhoogtoets\nom te springen."],
	"tutorial.jump.touch":		["Touch the top of the\nscreen to jump.",
												"Druk op de bovenkant van\nhet scherm om te springen."],
	"tutorial.jumpHeight":	["The higher the obstacle, the earlier\nyou need to start your jump.",
													"Hoe hoger de hindernis, hoe eerder\nje aan je sprong moet beginnen."],
	"tutorial.unjumpable":	["Some obstacles even you can't\njump over, and must go around.",
													"Sommige hindernissen kan zelfs jij\nniet overheen, en moet je ontwijken."],
	"tutorial.life":	["That's just not fair!\nBut don't worry, the big egg\nwill restore the lost life.",
							"Dat is gewoon oneerlijk!\nGelukkig zal het grote ei\nhet verloren leven herstellen."],
	"tutorial.killer":	["Watch out!\nSome obstacles will stop you\nin your tracks!",
													"Let op!\nSommige hindernissen\nmaken je in!"],
};
