var NONE = 0;
var BOX = 1;
var CIRCLE = 2;
var POLY = 3;

var NORMAL = 0;
var PLANK = 1;
var BALL = 2;
var LIMITER = 3;
var REDCANDY = 4;
var GREENCANDY = 5;
var REDMOB = 6;
var GREENMOB = 7;

function spritesSync(e, x, y)
{
	var p = new Vector(-e.target.syncX, -e.target.syncY);
	p.rotate(-e.target.rotation);
	e.target.x += p.x; 
	e.target.y += p.y;
}

var objects = [

{
	name: "wood_horizontal_1",
	image: "png_object/objects/wood_horizontal_1.png",
	type: PLANK,
	width: 86,
	height: 19,
	bodyWidth: 86,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_3",
	image: "png_object/objects/wood_horizontal_3.png",
	type: PLANK,
	width: 62,
	height: 19,
	bodyWidth: 62,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_3_dynamic",
	image: "png_object/objects/wood_horizontal_3.png",
	type: PLANK,
	width: 62,
	height: 19,
	bodyWidth: 62,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_4",
	image: "png_object/objects/wood_horizontal_4.png",
	type: PLANK,
	width: 42,
	height: 19,
	bodyWidth: 42,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_6",
	image: "png_object/objects/wood_horizontal_6.png",
	type: PLANK,
	width: 108,
	height: 19,
	bodyWidth: 108,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_7",
	image: "png_object/objects/wood_horizontal_7.png",
	type: PLANK,
	width: 87,
	height: 20,
	bodyWidth: 87,
	bodyHeight: 20,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_9",
	image: "png_object/objects/wood_horizontal_9.png",
	type: PLANK,
	width: 86,
	height: 20,
	bodyWidth: 86,
	bodyHeight: 20,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_10",
	image: "png_object/objects/wood_horizontal_10.png",
	type: PLANK,
	width: 99,
	height: 20,
	bodyWidth: 99,
	bodyHeight: 20,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_11",
	image: "png_object/objects/wood_horizontal_11.png",
	type: PLANK,
	width: 51,
	height: 17,
	bodyWidth: 51,
	bodyHeight: 17,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_12",
	image: "png_object/objects/wood_horizontal_12.png",
	type: PLANK,
	width: 105,
	height: 12,
	bodyWidth: 105,
	bodyHeight: 12,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_13",
	image: "png_object/objects/wood_horizontal_13.png",
	type: PLANK,
	width: 74,
	height: 13,
	bodyWidth: 74,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_14",
	image: "png_object/objects/wood_horizontal_14.png",
	type: PLANK,
	width: 72,
	height: 13,
	bodyWidth: 72,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_15",
	image: "png_object/objects/wood_horizontal_15.png",
	type: PLANK,
	width: 97,
	height: 13,
	bodyWidth: 97,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_15_dynamic",
	image: "png_object/objects/wood_horizontal_15.png",
	type: PLANK,
	width: 97,
	height: 13,
	bodyWidth: 97,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_16",
	image: "png_object/objects/wood_horizontal_16.png",
	type: PLANK,
	width: 79,
	height: 13,
	bodyWidth: 79,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_horizontal_17",
	image: "png_object/objects/wood_horizontal_17.png",
	type: PLANK,
	width: 133,
	height: 12,
	bodyWidth: 133,
	bodyHeight: 12,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_vertical_1",
	image: "png_object/objects/wood_vertical_1.png",
	type: PLANK,
	width: 19,
	height: 74,
	bodyWidth: 19,
	bodyHeight: 74,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_vertical_2",
	image: "png_object/objects/wood_vertical_2.png",
	type: PLANK,
	width: 20,
	height: 38,
	bodyWidth: 20,
	bodyHeight: 38,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_vertical_3",
	image: "png_object/objects/wood_vertical_3.png",
	type: PLANK,
	width: 13,
	height: 62,
	bodyWidth: 13,
	bodyHeight: 62,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_vertical_4",
	image: "png_object/objects/wood_vertical_4.png",
	type: PLANK,
	width: 13,
	height: 46,
	bodyWidth: 13,
	bodyHeight: 46,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_vertical_5",
	image: "png_object/objects/wood_vertical_5.png",
	type: PLANK,
	width: 13,
	height: 103,
	bodyWidth: 13,
	bodyHeight: 103,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_round",
	image: "png_object/objects/wood_round.png",
	type: PLANK,
	width: 38,
	height: 38,
	bodyWidth: 38,
	bodyHeight: 38,
	frames: 1,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_box",
	image: "png_object/objects/wood_box.png",
	type: PLANK,
	width: 38,
	height: 38,
	bodyWidth: 38,
	bodyHeight: 38,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_1",
	image: "png_object/objects/ice_block_1.png",
	type: PLANK,
	width: 71,
	height: 11,
	bodyWidth: 71,
	bodyHeight: 11,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.05,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_2",
	image: "png_object/objects/ice_block_2.png",
	type: PLANK,
	width: 53,
	height: 14,
	bodyWidth: 53,
	bodyHeight: 14,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_3",
	image: "png_object/objects/ice_block_3.png",
	type: PLANK,
	width: 104,
	height: 13,
	bodyWidth: 104,
	bodyHeight: 13,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_4",
	image: "png_object/objects/ice_block_4.png",
	type: PLANK,
	width: 10,
	height: 37,
	bodyWidth: 10,
	bodyHeight: 37,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_5",
	image: "png_object/objects/ice_block_5.png",
	type: PLANK,
	width: 8,
	height: 45,
	bodyWidth: 8,
	bodyHeight: 45,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.02,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_joint_1",
	image: "png_object/objects/ice_block_joint_1.png",
	type: PLANK,
	width: 12,
	height: 68,
	bodyWidth: 12,
	bodyHeight: 68,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_joint_2",
	image: "png_object/objects/ice_block_joint_2.png",
	type: PLANK,
	width: 11,
	height: 70,
	bodyWidth: 11,
	bodyHeight: 70,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ice_block_joint_3",
	image: "png_object/objects/ice_block_joint_3.png",
	type: PLANK,
	width: 56,
	height: 68,
	bodyWidth: 56,
	bodyHeight: 68,
	frames: 1,
	bodyType: POLY,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6,
	points: [
		[[-28, 34], [-28, 24], [28, 24], [28, 34]],
		[[19, 24], [19, -34], [28, -34], [28, 24]],
	]
},
{
	name: "ice_block_joint_4",
	image: "png_object/objects/ice_block_joint_4.png",
	type: PLANK,
	width: 56,
	height: 10,
	bodyWidth: 56,
	bodyHeight: 10,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.02,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_joint_1",
	image: "png_object/objects/wood_joint_1.png",
	type: PLANK,
	width: 13,
	height: 106,
	bodyWidth: 13,
	bodyHeight: 106,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_joint_1b",
	image: "png_object/objects/wood_joint_1b.png",
	type: PLANK,
	width: 13,
	height: 75,
	bodyWidth: 13,
	bodyHeight: 75,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_joint_2",
	image: "png_object/objects/wood_joint_2.png",
	type: PLANK,
	width: 10,
	height: 105,
	bodyWidth: 10,
	bodyHeight: 105,
	frames: 1,
	bodyType: BOX,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wood_joint_3",
	image: "png_object/objects/wood_joint_3.png",
	type: PLANK,
	width: 39,
	height: 102,
	bodyWidth: 39,
	bodyHeight: 102,
	frames: 1,
	bodyType: POLY,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6,
	points: [
		[[-5.5, 51], [-5.5, -13], [6, -13], [6, 51]],
		[[-19, -13], [-19, -51], [19, -51], [19, -13]],
	]
},
{
	name: "wood_joint_4",
	image: "png_object/objects/wood_joint_4.png",
	type: PLANK,
	width: 122,
	height: 77,
	bodyWidth: 122,
	bodyHeight: 77,
	frames: 1,
	bodyType: POLY,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6,
	points: [
		[[40, 38.5], [-61, -29], [-54, -38.5], [46, 29.5]],
		[[37.5, 23.5], [51, 3.5], [61, 9.5], [46, 29.5]],
	]
},
{
	name: "wood_joint_5",
	image: "png_object/objects/wood_joint_5.png",
	type: PLANK,
	width: 32,
	height: 32,
	bodyWidth: 32,
	bodyHeight: 32,
	frames: 1,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "rubber_block",
	image: "png_object/objects/rubber_block.png",
	type: PLANK,
	width: 76,
	height: 72,
	bodyWidth: 76,
	bodyHeight: 72,
	frames: 1,
	bodyType: POLY,
	fixed: true,
	density: 0.1,
	restitution: 0.9,
	friction: 0.6,
	points: [[[27, 36], [-38, -24], [-27, -36], [38, 24]]]
},


/*
{
	name: "limiter_up",
	image: "limiter_up.png",
	type: LIMITER,
	width: 22.5,
	height: 19,
	bodyWidth: 22.5,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "limiter_down",
	image: "limiter_down.png",
	type: LIMITER,
	width: 22.5,
	height: 19,
	bodyWidth: 22.5,
	bodyHeight: 19,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "limiter_main_1",
	image: "limiter_main_1.png",
	type: LIMITER,
	width: 12.5,
	height: 38,
	bodyWidth: 12.5,
	bodyHeight: 38,
	frames: 1,
	bodyType: BOX,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "wheel",
	image: "wheel.png",
	type: LIMITER,
	width: 22.5,
	height: 22,
	bodyWidth: 22.5,
	bodyHeight: 22,
	frames: 1,
	bodyType: CIRCLE,
	fixed: true,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},*/
{
	name: "green_wait_1",
	image: "png_object/objects/green_wait_1.png",
	type: GREENMOB,
	width: 34,
	height: 34,
	bodyWidth: 34,
	bodyHeight: 34,
	frames: 18,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.2,
	restitution: 0.4,
	friction: 0.6
},
{
	name: "red_wait_1",
	image: "png_object/objects/red_wait_1.png",
	type: REDMOB,
	width: 32,
	height: 32,
	bodyWidth: 32,
	bodyHeight: 32,
	frames: 28,
	//layers: 2,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.2,
	restitution: 0.4,
	friction: 0.6
},
{
	name: "green_wait_2",
	image: "png_object/objects/green_wait_2.png",
	type: GREENMOB,
	width: 34,
	height: 34,
	bodyWidth: 34,
	bodyHeight: 34,
	frames: 17,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "red_wait_2",
	image: "png_object/objects/red_wait_2.png",
	type: REDMOB,
	width: 32,
	height: 32,
	bodyWidth: 32,
	bodyHeight: 32,
	frames: 17,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "red_happy",
	image: "png_object/objects/red_happy.png",
	type: REDMOB,
	width: 44,
	height: 44,
	bodyWidth: 44,
	bodyHeight: 44,
	frames: 19,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.3,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "green_happy",
	image: "png_object/objects/green_happy.png",
	type: GREENMOB,
	width: 46,
	height: 44,
	bodyWidth: 46,
	bodyHeight: 44,
	frames: 22,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "red_candy",
	image: "png_object/objects/red_candy.png",
	type: REDCANDY,
	width: 26,
	height: 26,
	bodyWidth: 26,
	bodyHeight: 26,
	frames: 1,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "green_candy",
	image: "png_object/objects/green_candy.png",
	type: GREENCANDY,
	width: 26,
	height: 26,
	bodyWidth: 26,
	bodyHeight: 26,
	frames: 1,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.2,
	friction: 0.6
},
{
	name: "ball",
	image: "png_object/objects/ball.png",
	type: BALL,
	width: 23,
	height: 23,
	bodyWidth: 23,
	bodyHeight: 23,
	frames: 1,
	bodyType: CIRCLE,
	fixed: false,
	density: 0.1,
	restitution: 0.01,
	friction: 0.6
}


];